const mongoose=require("mongoose")
const courseSchema=new mongoose.Schema({
    coursename:{
        type:String,
        required:true
    },
    coursedescription:{
        type:String,
        required:true
    },
    instructor:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"user",
        required:true
    },
    whatyouwilllearn:{
        type:String,
        required:String
    },
    coursecontent:[{
        type:mongoose.Schema.Types.ObjectId,
        ref:"section",
    }],
    ratingandreview:[{
        type:mongoose.Schema.Types.ObjectId,
            ref:"RatingAndReview"
        }
    ],
    price:{
        type:String,
        required:true
    },
   
    thumbnails:{
        type:String,
        // required:true
    },
    category:{
        type:mongoose.Schema.Types.ObjectId, 
        ref:"category"
    },
    tag:{
        type:[String]
    },
    studentEnrolled:[{
        type:mongoose.Schema.Types.ObjectId, 
        ref:"user"
    }], 
    instruction:{
        type:[String],
        required:true 
    },
    status:{
        type:String, 
        enum:["Draft","Published"]
    },
    createdAt:{
        type:Date,
        default:Date.now()
    }
   
})
module.exports=mongoose.model("courses",courseSchema)