const mongoose=require('mongoose')
const userSchema=new mongoose.Schema({
    firstName:{
        type:String,
        required:true,
        trim:true
    },
    lastName:{
        type:String,
        required:true,
        trim:true
    },
    email:{
        type:String,
        required:true,
        trim:true
    },
    password:{
        type:String,
        required:true
    },
    confirmpassword:{
        type:String,
        required:true
    },
    role:{
        type:String,
        enum:["Student","Instructor","Admin"]
    },
    additionalDetails:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"Profile",
        required:true
    },
  
    courses:[{
        type:mongoose.Schema.Types.ObjectId,
        ref:"courses",
        required:true
    }],
    image:{
        type:String,
        required:true
    },   
    courseProgress:[
        {
        type:mongoose.Schema.Types.ObjectId,
        ref:"courseProgress",
        }
    ],
    token:{
        type:String
    },
    resetPasswordExpires:{
        type:Date
    }
})
module.exports=mongoose.model("user",userSchema)